### ISSUE TITLE
webassembly

### ISSUE THREAD

**Issue by haoxinst** [haoxins/haoxins.github.io#21]
https://github.com/ElixiumNetwork/WaspVM

**Comment by haoxinst** [comment]
https://rustwasm.github.io

https://rustwasm.github.io/wasm-pack

https://rustwasm.github.io/wasm-bindgen

**Comment by haoxins** [comment]
https://github.com/nathan/pax

**Comment by haoxins** [comment]
https://github.com/astrolang/astro
