### ISSUE TITLE
2019-02 blockchain todo list

### ISSUE THREAD

**Issue by haoxinst** [haoxins/haoxins.github.io#23]
### BFT

- [pdf: The latest gossip on BFT consensus](https://arxiv.org/pdf/1807.04938.pdf)
- [Consensus Compare: Casper vs. Tendermint](https://blog.cosmos.network/consensus-compare-casper-vs-tendermint-6df154ad56ae)
- [DPOS BFT— Pipelined Byzantine Fault Tolerance](https://medium.com/eosio/dpos-bft-pipelined-byzantine-fault-tolerance-8a0634a270ba)

* multihash

- [multihash](https://github.com/multiformats/multihash)

### CRDT

* [CRDT - An introduction to state-based CRDTs](https://bartoszsypytkowski.com/the-state-of-a-state-based-crdts)
* [ipfs - CRDT research](https://github.com/ipfs/research-CRDT)
* [pfrazee - CRDT notes](https://github.com/pfrazee/crdt_notes)

### Platforms

* [Next-generation framework for blockchain innovation](https://github.com/paritytech/substrate)
* [Tendermint Core (BFT Consensus) in Go](https://github.com/tendermint/tendermint)

https://github.com/aeternity

* Noise protocol
  - [Website](http://noiseprotocol.org)
  - [Github](https://github.com/noiseprotocol)

**Comment by haoxinst** [comment]
https://w3c-ccg.github.io/did-spec/

**Comment by haoxins** [comment]
https://github.com/mimblewimble/grin
