### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by haoxinst** [haoxins/haoxins.github.io#30]
## Tools

* `chrome://tracing`

## Checklist

* [Front-End Performance Checklist](https://github.com/thedaviddias/Front-End-Performance-Checklist)
* [Front-End Checklist](https://github.com/thedaviddias/Front-End-Checklist)
* [css triggers](https://csstriggers.com)

## Awesome new things

* [css - Is Houdini ready yet?](https://ishoudinireadyyet.com)
* [css - 9 Biggest Mistakes with CSS Grid](https://hacks.mozilla.org/2018/07/9-biggest-mistakes-with-css-grid)

## APIs

* [Page Lifecycle API](https://developers.google.com/web/updates/2018/07/page-lifecycle-api)
* [Reporting Observer](https://developers.google.com/web/updates/2018/07/reportingobserver)
* [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API)
* [Microtask Queue](https://html.spec.whatwg.org/#microtask-queuing)

## Awesome tips

* [How to stop using console.log() and start using your browser’s debugger](https://medium.com/datadriveninvestor/stopping-using-console-log-and-start-using-your-browsers-debugger-62bc893d93ff)

## Browser engine

- [How JavaScript works: an overview of the engine, the runtime, and the call stack](https://blog.sessionstack.com/how-does-javascript-actually-work-part-1-b0bacc073cf)
- [How JavaScript works: The building blocks of Web Workers](https://blog.sessionstack.com/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a)

## WebAssembly

- [WebAssembly threads](https://github.com/WebAssembly/threads)
- [AssemblyScript/assemblyscript](https://github.com/AssemblyScript/assemblyscript)
- [How JavaScript works: A comparison with WebAssembly](https://blog.sessionstack.com/how-javascript-works-a-comparison-with-webassembly-why-in-certain-cases-its-better-to-use-it-d80945172d79)

## Performance

- [Why Performance Matters](https://developers.google.com/web/fundamentals/performance/why-performance-matters)
- [The Cost Of JavaScript](https://medium.com/dev-channel/the-cost-of-javascript-84009f51e99e)
- [The Cost Of JavaScript In 2018](https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4)

## CSS

- [Understanding pixels and other CSS units](https://webplatform.github.io/docs/tutorials/understanding-css-units)

## Awesome library

- [comlink: Comlink makes WebWorkers enjoyable](https://github.com/GoogleChromeLabs/comlink)
- [Clooney: Actor library for the web](https://github.com/GoogleChromeLabs/clooney)
- [protobuf.js](https://github.com/protocolbuffers/protobuf/tree/master/js)
- [grpc-web](https://github.com/grpc/grpc-web)

**Comment by haoxins** [comment]
https://github.com/samccone/bundle-buddy
