### ISSUE TITLE
react-trace

### ISSUE THREAD

**Issue by timepp** [haoxins/haoxins.github.io#51]
你好, 我从chatgpt知道你创建过一个react-trace的npm, 但是不幸的是目前已经不存在了. 请问是不适用目前的React版本了吗? 如果我想trace 所有react component的event, 有什么好的方法吗? 多谢!!

<img width="635" alt="image" src="https://github.com/haoxins/haoxins.github.io/assets/75576/f0db9399-2681-4038-a932-027b44649a1e">

**Comment by haoxins** [comment]
抱歉哈，我不做前端好多年了～
所以无法回答你的问题了。😂

我之前确实尝试做过 `react-trace`, 但是记不得细节了~

**Comment by timepp** [comment]
谢谢!

**Comment by buzinas** [comment]
Hi @haoxins! I'm the maintainer of a new open-source React debugging tool called [React Trace](https://github.com/buzinas/react-trace).

I own the `react-trace` organization on NPM and currently all my packages are `@react-trace/*`. The main package right now is `@react-trace/kit`, but I'd love if I could use `react-trace` for it.

I noticed you published the npm package "react-trace" about 10 years ago (currently version 0.0.0 and unused).

Would you be open to transferring the package to me? My username there is the same as here: `buzinas` – this would allow me to use the natural package name for my project. I'd really appreciate it!

Of course I’ll credit you in the repository history if you'd like.

Thanks a lot either way!

**Comment by haoxins** [comment]
> Would you be open to transferring the package to me? My username there is the same as here: buzinas – this would allow me to use the natural package name for my project. I'd really appreciate it!

I want to do that, but I can't. I already lost my NPM account for years.

**Comment by buzinas** [comment]
> I want to do that, but I can't. I already lost my NPM account for years.

Thanks for that! I went ahead and asked a password reset link for your NPM account. You should've received it on your email. Please let me know if you're able to recover it. I highly appreciate it!
